openapi: 3.2.0
info:
  title: Insider Mobile App APIs API
  version: 1.0.0
  contact:
    name: Insider One Support
    email: support@useinsider.com
    url: https://academy.insiderone.com/docs/insider-one-apis-1
  termsOfService: https://insiderone.com/terms-of-use/
  description: 'Operations tagged Mobile App APIs across 2 of this provider''s published API definitions: insider-mobile-openapi.yml, insider-mobile-settings-openapi.yml. Each path carries the servers of the definition it was published in.'
servers:
- url: https://mobile.useinsider.com
- url: https://mobile.api.useinsider.com
tags:
- name: Mobile App APIs
paths:
  /api/custom_segment/v1/upload:
    post:
      operationId: uploadCustomSegmentsToMobileSuite
      summary: Upload custom segments to mobile suite
      description: Upload custom segments via a CSV file to your Insider One Mobile Suite.
      tags:
      - Mobile App APIs
      security:
      - RequestToken: []
      - PartnerName: []
      responses:
        '429':
          $ref: '#/components/responses/TooManyRequests'
      x-source: https://academy.insiderone.com/docs/insider-one-apis-1
      x-source-note: Documented in the Insider One APIs overview table but not present in the public Postman collection; method, host and path taken verbatim from that table.
    servers:
    - url: https://mobile.useinsider.com
  /api/message_center/v1:
    post:
      operationId: getMessageCenterData
      summary: Get Message Center data
      tags:
      - Mobile App APIs
      description: 'This API allows you to get the push notifications of any type delivered to your users during a defined time interval, including the push notifications delivered in Architect journeys.


        Body Parameters

        Before sending the request, make sure to replace the values in your request body.


        Parameter

        Description

        Data Type

        Required


        identifiers

        User''s identifier information. Identifiers can be Email, Phone Number, UUID (unique user ID), or a custom identifier. The identifiers need to be written in the mentioned letter cases in the request, while the custom attribute needs to be written in the attribute_name format.

        Object

        Yes


        start_date

        Start date of the timeline push notifications are delivered within, in timestamp format.

        Integer

        Yes


        end_date

        End date of the timeline push notifications are delivered within, in timestamp format.

        Integer

        Yes


        limit

        Number of push notifications you can get in one request. The value can be between1-100.

        Integer

        Yes


        Sample Body

        The following is a sample body to get your message center data.


        {

        "identifiers": {

        "Email": "j.doe@mail.com"

        },

        "start_date": 1633068172,

        "end_date": 2143433430,

        "limit": 100

        }


        Sample Responses

        200 OK

        The following sample response returns for a successful request with a limit of 3.


        [

        {

        "camp_id": 650,

        "camp_type": "Single Push",

        "created_at": "2023-01-23T18:10:17Z",

        "deep_links": {

        "Page": "Cart",

        "category": "insider_int_push",

        "mutable-content": "1"

        },

        "message": "This is my message",

        "title": "This is my title",

        "variant_id": 1907

        },

        {

        "camp_id": 101,

        "camp_type": "Recurring Push",

        "created_at": "2023-01-18T21:00:21Z",

        "deep_links": {

        "MyKey01": "MyValue01"

        },

        "message": "New women''s clothing has launched...",

        "title": "Don''t forget about me!",

        "variant_id": 898

        },

        {

        "camp_id": 132,

        "camp_type": "Recurring Push",

        "created_at": "2023-01-18T21:00:20Z",

        "deep_links": {

        "Page": "Cart",

        "MyKey02": "MyValue02"

        },

        "message": "Your favorite items are waiting for you. ",

        "title": "Retail",

        "variant_id": 1122

        }

        ]


        400 Bad Request

        The following sample response returns for a request where the start date is greater than the end date.


        bad payload


        400 Bad Request

        The following sample response returns for a request where the limit is greater than 100.


        limit should be between 1 and 100.


        401 Unauthorized

        A request with an invalid API key will return a 401 Unauthorized response.


        Limitations

        When sending your request, make sure to follow these limitations.


        All functions must be executed with a simple HTTPS POST request.


        Each request can get push notifications only for one single user.'
      security:
      - InsiderApiKey: []
      requestBody:
        content:
          application/json:
            example:
              identifiers:
                Email: j.doe@mail.com
              start_date: 1633068172
              end_date: 2143433430
              limit: 100
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
              - camp_id: 897
                camp_type: Single Push
                created_at: '2023-05-10T19:08:39Z'
                deep_links:
                  key1: value1
                image_url: https://imageurl.useinsider.com
                message: This is my message!
                title: This is my title
                variant_id: 1943
              - camp_id: 896
                camp_type: Single Push
                created_at: '2023-05-09T22:10:56Z'
                deep_links:
                  key2: value2
                image_url: https://imageurl.useinsider.com
                message: This is my great message
                title: This is my amazing title
                variant_id: 1941
              - camp_id: 894
                camp_type: Single Push
                created_at: '2023-05-08T23:55:45Z'
                deep_links:
                  key3: value3
                message: This is my message
                title: This is my title
                variant_id: 1937
        '429':
          $ref: '#/components/responses/TooManyRequests'
    servers:
    - url: https://mobile.useinsider.com
  /api/v1/push/bulk:
    post:
      operationId: sendBulkAppPushes
      summary: Send bulk app pushes
      tags:
      - Mobile App APIs
      description: Bulk Push API is a service that sends push notifications to a predefined segment over the web using predefined web services.
      requestBody:
        content:
          application/json:
            example:
              api_key: '{mobileAppApiKey}'
              campaign_name: Insider API Demo
              segment_name: Your segment name goes here
              title: Your push notification title goes here
              content: Your push content goes here.
              deeplink:
                your_deeplink_key: value
                your_another_deeplink_key: value
              notification_image: https://your_image_url.jpg
              android_sound: Your custom sound name for Android goes here
              ios_sound: Your custom sound name for iOS goes here
              test_push: true
              override_global_freq_cap: true
              advanced_push_items:
              - headline: Title for the item 1
                description: Description for the item 1
                image_url: https://your_image_url.jpg
                deep_links:
                  your_deeplink_key: value
              - headline: Title for the item 2
                description: Description for the item 2
                image_url: https://your_image_url.jpg
                deep_links:
                  your_deeplink_key: value
              - headline: Title for the item 3
                description: Description for the item 3
                image_url: https://your_image_url.jpg
                deep_links:
                  your_deeplink_key: value
              preferred_type: carousel
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                default:
                  value:
                    response: Test Push Send to Test Devices
                send-advanced-bulk-push-to-a-segment:
                  value:
                    response: Campaign Created
        '429':
          $ref: '#/components/responses/TooManyRequests'
    servers:
    - url: https://mobile.useinsider.com
  /api/v2/notification/user:
    post:
      operationId: sendTargetedAppPushes
      summary: Send targeted app pushes
      tags:
      - Mobile App APIs
      description: You can use the Targeted Push API in various cases such as sending status update of an order from your ecommerce platform, or informing users of a sale on an item that was in their wishlist.
      requestBody:
        content:
          application/json:
            examples:
              default:
                value:
                  api_key: '{mobileAppApiKey}'
                  report_attributes:
                  - INSIDER.carrier
                  - INSIDER.idfa
                  - INSIDER.name
                  - INSIDER.surname
                  - INSIDER.gender
                  - INSIDER.age
                  - INSIDER.birthday
                  - INSIDER.email
                  - INSIDER.phone_number
                  - INSIDER.language
                  - INSIDER.email_optin
                  - INSIDER.sms_optin
                  - INSIDER.push_optin
                  - INSIDER.location_optin
                  - INSIDER.insider_id
                  - INSIDER.environment
                  - INSIDER.idfa
                  - INSIDER.device_token
                  - INSIDER.udid
                  - INSIDER.model
                  - INSIDER.carrier
                  - INSIDER.app_version
                  - INSIDER.os_version
                  - INSIDER.screen_width
                  - INSIDER.screen_height
                  - INSIDER.platform
                  - INSIDER.timezone
                  - INSIDER.device_language
                  - INSIDER.sdk_version
                  - INSIDER.last_ip
                  - INSIDER.package_name
                  - INSIDER.push_enabled
                  - INSIDER.location_enabled
                  notifications:
                  - identifiers:
                      INSIDER.email: sample@useinsider.com
                      INSIDER.phone_number: '+65123456789'
                      INSIDER.uuid: '1234567890'
                    camp_id: 1
                    camp_name: Your push notification campaign name goes here
                    title: Your push notification title goes here
                    message: Your push content goes here.
                    image_url: https://your_image_url.jpg
                    ttl: 1
                    check_optin: true
                    android:
                      thread-id: 1
                      sound: sound_check
                      deep_link:
                        ins_dl_internal: https://www.deeplink.useinsider
                    ios:
                      thread-id: 1
                      badge: 1
                      content-available: false
                      mutable-content: true
                      sound: sound_check
                      deep_link:
                        ins_dl_internal: https://www.deeplink.useinsider
              send-advanced-app-pushes:
                summary: Send advanced app pushes
                value:
                  api_key: '{mobileAppApiKey}'
                  report_attributes:
                  - INSIDER.carrier
                  - INSIDER.idfa
                  - INSIDER.name
                  - INSIDER.surname
                  - INSIDER.gender
                  - INSIDER.age
                  - INSIDER.birthday
                  - INSIDER.email
                  - INSIDER.phone_number
                  - INSIDER.language
                  - INSIDER.email_optin
                  - INSIDER.sms_optin
                  - INSIDER.push_optin
                  - INSIDER.location_optin
                  - INSIDER.insider_id
                  - INSIDER.environment
                  - INSIDER.idfa
                  - INSIDER.device_token
                  - INSIDER.udid
                  - INSIDER.model
                  - INSIDER.carrier
                  - INSIDER.app_version
                  - INSIDER.os_version
                  - INSIDER.screen_width
                  - INSIDER.screen_height
                  - INSIDER.platform
                  - INSIDER.timezone
                  - INSIDER.device_language
                  - INSIDER.sdk_version
                  - INSIDER.last_ip
                  - INSIDER.package_name
                  - INSIDER.push_enabled
                  - INSIDER.location_enabled
                  notifications:
                  - identifiers:
                      INSIDER.email: sample@useinsider.com
                      INSIDER.phone_number: '+6559713551597135123'
                      INSIDER.uuid: '5971351231234567'
                    advanced_push_payload:
                      advanced_push_type: carousel
                      advanced_push_items:
                      - image_url: https://your_image_url.jpg
                        deep_links:
                          your_deeplink_key: value1
                        description: Description for the item 1
                        headline: Title for the item 1
                        id: 1
                      - image_url: https://your_image_url.jpg
                        deep_links:
                          your_deeplink_key: value2
                        description: Description for the item 2
                        headline: Title for the item 2
                        id: 2
                      - image_url: https://your_image_url.jpg
                        deep_links:
                          your_deeplink_key: value3
                        description: Description for the item 3
                        headline: Title for the item 3
                        id: 3
                    camp_id: 1
                    camp_name: Your push notification campaign name goes here
                    title: Your push notification title goes here
                    message: Your push content goes here
                    image_url: https://your_image_url.jpg
                    ttl: 1
                    check_optin: true
                    android:
                      thread-id: 1
                      sound: sound_check
                      deep_link:
                        ins_dl_internal: https://www.deeplink.useinsider
                    ios:
                      thread-id: 13
                      badge: 1
                      deliver_silently: true
                      mutable-content: true
                      sound: sound_check
                      content-available: true
                      deep_link:
                        ins_dl_internal: https://www.deeplink.useinsider
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                default:
                  value:
                    successes: []
                    errors:
                      NoUserFound:
                      - INSIDER.uuid: u1u2i3d4
                send-targeted-app-push:
                  value:
                    successes:
                    - INSIDER.app_version: '10.0'
                      INSIDER.birthday: null
                      INSIDER.carrier: Turkcell
                      INSIDER.device_language: en
                      INSIDER.email: sample@useinsider.com
                      INSIDER.email_optin: true
                      INSIDER.environment: production
                      INSIDER.insider_id: 1234-5678-9012
                      INSIDER.language: en_US
                      INSIDER.location_optin: false
                      INSIDER.model: iPhone 11
                      INSIDER.os_version: '16.3'
                      INSIDER.phone_number: '+16102362339'
                      INSIDER.platform: iOS
                      INSIDER.push_optin: true
                      INSIDER.sdk_version: 12.7.3-RN-5.5.0
                      INSIDER.sms_optin: true
                      INSIDER.timezone: Europe/Istanbul
                      INSIDER.udid: u1u2i3d4
                    errors: {}
              example:
                successes:
                - INSIDER.birthday: null
                  INSIDER.device_language: en
                  INSIDER.email: sample@useinsider.com
                  INSIDER.language: en_US
                  INSIDER.model: iPhone 11
                  INSIDER.phone_number: '+16102362339'
                  INSIDER.sdk_version: 12.7.3-RN-5.5.0
                errors: {}
        '429':
          $ref: '#/components/responses/TooManyRequests'
    servers:
    - url: https://mobile.useinsider.com
  /v1/details/inapp:
    post:
      operationId: getInappCampaignDetails
      summary: Get inapp campaign details
      tags:
      - Mobile App APIs
      description: This API allows you to retrieve detailed information about your app template campaigns.
      security:
      - ApiKey: []
      requestBody:
        content:
          application/json:
            example:
              created_between:
                from: '2025-01-16'
                to: '2025-04-15'
      responses:
        '429':
          $ref: '#/components/responses/TooManyRequests'
    servers:
    - url: https://mobile.api.useinsider.com
  /v1/settings/certificate/firebase:
    post:
      operationId: uploadFcmCertificate
      summary: Upload FCM certificate
      tags:
      - Mobile App APIs
      description: This API allows you to upload your FCM certificate to Insider without visiting the Inone panel. With this API, you can upload or change your certificate.
      security:
      - ApiKey: []
      requestBody:
        content:
          text/plain:
            example: "{\n  \"type\": \"service_account\",\n  \"project_id\": \"certificate-id\",\n  \"private_key_id\": \"01ab23cd45ef\",\n  \"private_key\": \"-----BEGIN PRIVATE KEY-----\\abcdef123456\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"firebase-admin-abc123@insider-sdk.iam.gserviceaccount.com\",\n  \"client_id\": \"1234567890\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_uri\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"https://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www.googleapis.com/robot/v1/metadata/x509/firebase-admin-abc123-%insider-sdk.iam.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}"
      responses:
        '429':
          $ref: '#/components/responses/TooManyRequests'
    servers:
    - url: https://mobile.api.useinsider.com
components:
  responses:
    TooManyRequests:
      description: Too Many Requests. The published per-endpoint rate limit was exceeded; back off and retry, honouring Retry-After when present.
      content:
        application/json:
          example:
            message: Too Many Requests
            status: 429
  securitySchemes:
    InsiderApiKey:
      type: apiKey
      in: header
      name: X-INSIDER-API-KEY
      description: Insider One API key for this API.
    ApiKey:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Insider One API key for this API.
externalDocs:
  description: Insider One API reference
  url: https://academy.insiderone.com/docs/api-reference-welcome
x-refined-from:
- insider-mobile-openapi.yml
- insider-mobile-settings-openapi.yml
x-provenance:
  generated: '2026-08-13'
  method: derived
  source: postman/insider-one-apis.postman_collection.json
  source_url: https://documenter.gw.postman.com/api/collections/24851117/2sB3dSR9bM
  publisher_page: https://developers.insiderone.com/
  note: Insider One publishes a single public Postman collection covering every REST API. This document is the subset of that collection served from analytics.api.useinsider.com.
